In [ ]:
from infostop import Infostop
import numpy as np
import polars as pl
from pyproj import Transformer

import yaml

In [46]:
with open("../config.yaml") as fp:
    config = yaml.safe_load(fp)

In [ ]:
# stop detection process
with open("05_detect_stops_config.yaml") as fp:
    params = yaml.safe_load(fp)["infostop"]

model = Infostop(
    r1=params["r1"],
    r2=params["r2"],
    min_staying_time=params["min_staying_time"],
    max_time_between=params["max_time_between"],
    min_size=params["min_size"],
    distance_metric=params["distance_metric"],
)

In [ ]:
transformer = Transformer.from_crs(4326, config["crs"])

In [3]:
def initial_filter(df: pl.DataFrame, min_pings: int) -> pl.DataFrame:
    """Keep only devices with at least min_pings pings."""
    valid_devices = (
        df.group_by("device_id")
        .len()
        .filter(pl.col("len") >= min_pings)["device_id"]
        .to_list()
    )
    return df.filter(pl.col("device_id").is_in(valid_devices))

In [5]:
data = pl.read_parquet(
    "/mnt/common-hdd/group-dirs/tkom-2026-project/partitioned/00/pings.parquet"
)

In [ ]:
filtered = initial_filter(data, min_pings=config["filtering"]["min_pings_per_day"])
filtered = filtered.with_columns(
    pl.col("timestamp").dt.epoch(time_unit="s").alias("epoch")
)

In [17]:
# run infostop per device — data already sorted, no re-sort needed in loop
# catch devices with no stop events (all pings labelled -1)
results = []
for device_id, group in filtered.group_by("device_id"):
    coords = group[["latitude", "longitude", "epoch"]].to_numpy()
    try:
        labels = model.fit_predict(coords)
    except Exception:
        labels = np.full(len(coords), -1)
    group_ = group.with_columns(place_label=labels)

    results.append(group_)

clustered = pl.concat(results)
clustered = clustered.sort(["device_id", "timestamp"])

n_stopped = (clustered["place_label"] >= 0).sum()
print(
    f"Stop pings:    {n_stopped:,}  ({n_stopped / len(clustered):.1%} of filtered pings)"
)
print(f"Unique stops:  {clustered['place_label'].clip(lower_bound=0).n_unique():,}")
clustered.head(3)

Stop pings:    9,474,653  (61.3% of filtered pings)
Unique stops:  393

shape: (3, 7)
┌─────────────────┬───────────┬─────────────────┬───────────┬───────────┬────────────┬─────────────┐
│ timestamp       ┆ device_id ┆ device_aid_type ┆ latitude  ┆ longitude ┆ epoch      ┆ place_label │
│ ---             ┆ ---       ┆ ---             ┆ ---       ┆ ---       ┆ ---        ┆ ---         │
│ datetime[μs,    ┆ i64       ┆ str             ┆ f64       ┆ f64       ┆ i64        ┆ i64         │
│ Europe/Budapest ┆           ┆                 ┆           ┆           ┆            ┆             │
│ ]               ┆           ┆                 ┆           ┆           ┆            ┆             │
╞═════════════════╪═══════════╪═════════════════╪═══════════╪═══════════╪════════════╪═════════════╡
│ 2024-10-02      ┆ 1         ┆ AAID            ┆ 47.47992  ┆ 19.074155 ┆ 1727829429 ┆ 2           │
│ 02:37:09 CEST   ┆           ┆                 ┆           ┆           ┆            ┆             │
│ 2024-10-02      ┆ 1         ┆ AAID            ┆ 47.479995 ┆ 19.074221 ┆ 1727831869 ┆ 2           │
│ 03:17:49 CEST   ┆           ┆                 ┆           ┆           ┆            ┆             │
│ 2024-10-02      ┆ 1         ┆ AAID            ┆ 47.476752 ┆ 19.075154 ┆ 1727832410 ┆ -1          │
│ 03:26:50 CEST   ┆           ┆                 ┆           ┆           ┆            ┆             │
└─────────────────┴───────────┴─────────────────┴───────────┴───────────┴────────────┴─────────────┘

In [ ]:
clustered.drop("epoch").write_parquet(
    "/mnt/common-hdd/group-dirs/tkom-2026-project/clustered_pings/00.parquet"
)

In [7]:
clustered = pl.read_parquet(
    "/mnt/common-hdd/group-dirs/tkom-2026-project/clustered_pings/00.parquet"
)

In [ ]:
clustered = clustered.with_columns(
    pl.when(pl.col("place_label") >= 0)
    .then(
        (
            (pl.col("place_label") >= 0)
            & (pl.col("place_label").shift(1).over("device_id").fill_null(-1) < 0)
        )
        .cast(pl.Int32)
        .cum_sum()
        .over("device_id")
    )
    .otherwise(-1)
    .alias("stop_id")
)

In [29]:
place_lable_jt = (
    clustered.filter(pl.col.stop_id >= 0)[["device_id", "stop_id", "place_label"]]
    .unique()
    .sort(["device_id", "stop_id"])
)

In [ ]:
clustered.filter((pl.col.stop_id == 4) & (pl.col.device_id == 1))

shape: (6, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ timestamp  ┆ device_id ┆ device_ai ┆ latitude  ┆ … ┆ place_lab ┆ stop_id ┆ latitude_ ┆ longitude │
│ ---        ┆ ---       ┆ d_type    ┆ ---       ┆   ┆ el        ┆ ---     ┆ proj      ┆ _proj     │
│ datetime[μ ┆ i64       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ i32     ┆ ---       ┆ ---       │
│ s, Europe/ ┆           ┆ str       ┆           ┆   ┆ i64       ┆         ┆ f64       ┆ f64       │
│ Budapest]  ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.509079 ┆ … ┆ 20        ┆ 4       ┆ 657828.48 ┆ 240577.30 │
│ 08:57:56   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 2382      ┆ 0753      │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.509079 ┆ … ┆ 20        ┆ 4       ┆ 657828.48 ┆ 240577.30 │
│ 09:17:56   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 2382      ┆ 0753      │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.509079 ┆ … ┆ 20        ┆ 4       ┆ 657828.48 ┆ 240577.30 │
│ 09:52:28   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 2382      ┆ 0753      │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.661187 ┆ … ┆ 3         ┆ 4       ┆ 652172.70 ┆ 257483.68 │
│ 09:52:53   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 8182      ┆ 671       │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.661213 ┆ … ┆ 3         ┆ 4       ┆ 652167.90 ┆ 257486.57 │
│ 10:23:47   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 0066      ┆ 5707      │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 2024-10-02 ┆ 1         ┆ AAID      ┆ 47.66122  ┆ … ┆ 3         ┆ 4       ┆ 652161.59 ┆ 257487.35 │
│ 10:33:00   ┆           ┆           ┆           ┆   ┆           ┆         ┆ 0488      ┆ 174       │
│ CEST       ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [ ]:
projected = transformer.transform(clustered["latitude"], clustered["longitude"])
clustered = clustered.with_columns(
    latitude_proj=projected[0], longitude_proj=projected[1]
)

In [ ]:
stops = (
    clustered.filter(pl.col.stop_id >= 0)
    .group_by(["device_id", "stop_id"])
    .agg(
        interval_start=pl.col.timestamp.min(),
        interval_stop=pl.col.timestamp.max(),
        interval_lenght=pl.col.timestamp.max() - pl.col.timestamp.min(),
        latitude_mean=pl.col.latitude.mean(),
        longitude_mean=pl.col.longitude.mean(),
        latitude_std=pl.col.latitude_proj.std().round(),
        longitude_std=pl.col.longitude_proj.std().round(),
        number_of_pings=pl.col.longitude.count(),
    )
    .join(place_lable_jt, on=["device_id", "stop_id"])
    .sort(["device_id", "stop_id"])
)
stops.write_parquet("/mnt/common-hdd/group-dirs/tkom-2026-project/stops/00.parquet")
stops

shape: (517_263, 11)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id ┆ stop_id ┆ interval_s ┆ interval_ ┆ … ┆ latitude_ ┆ longitude ┆ number_of ┆ place_lab │
│ ---       ┆ ---     ┆ tart       ┆ stop      ┆   ┆ std       ┆ _std      ┆ _pings    ┆ el        │
│ i64       ┆ i32     ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆         ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ u32       ┆ i64       │
│           ┆         ┆ s, Europe/ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ Budapest]  ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 1       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 6.0       ┆ 2         ┆ 2         │
│           ┆         ┆ 02:37:09   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 03:17:49  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 2       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 10.0      ┆ 65.0      ┆ 3         ┆ 2         │
│           ┆         ┆ 05:30:54   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 06:30:49  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 3       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 2.0       ┆ 14.0      ┆ 5         ┆ 3         │
│           ┆         ┆ 07:03:24   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 07:35:29  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 4       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 3101.0    ┆ 9261.0    ┆ 6         ┆ 20        │
│           ┆         ┆ 08:57:56   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 4       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 3101.0    ┆ 9261.0    ┆ 6         ┆ 3         │
│           ┆         ┆ 08:57:56   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 6584      ┆ 144     ┆ 2024-11-17 ┆ 2024-11-1 ┆ … ┆ 13.0      ┆ 22.0      ┆ 9         ┆ 3         │
│           ┆         ┆ 08:23:14   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 09:17:42  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 6584      ┆ 145     ┆ 2024-11-17 ┆ 2024-11-1 ┆ … ┆ 5.0       ┆ 13.0      ┆ 15        ┆ 3         │
│           ┆         ┆ 09:45:35   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 15:51:24  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 6584      ┆ 146     ┆ 2024-11-17 ┆ 2024-11-1 ┆ … ┆ 32.0      ┆ 21.0      ┆ 13        ┆ 3         │
│           ┆         ┆ 17:57:33   ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 21:46:42  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 6584      ┆ 147     ┆ 2024-11-17 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 1.0       ┆ 13        ┆ 3         │
│           ┆         ┆ 23:11:53   ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 05:13:19  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 6584      ┆ 148     ┆ 2024-11-18 ┆ 2024-11-1 ┆ … ┆ 7.0       ┆ 10.0      ┆ 18        ┆ 3         │
│           ┆         ┆ 06:13:07   ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 09:43:51  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
stops.filter(pl.col.device_id == 1)

shape: (110, 11)
┌───────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id ┆ stop_id ┆ interval_s ┆ interval_ ┆ … ┆ latitude_ ┆ longitude ┆ number_of ┆ place_lab │
│ ---       ┆ ---     ┆ tart       ┆ stop      ┆   ┆ std       ┆ _std      ┆ _pings    ┆ el        │
│ i64       ┆ i32     ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆         ┆ datetime[μ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ u32       ┆ i64       │
│           ┆         ┆ s, Europe/ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ Budapest]  ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1         ┆ 1       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 6.0       ┆ 2         ┆ 2         │
│           ┆         ┆ 02:37:09   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 03:17:49  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 2       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 10.0      ┆ 65.0      ┆ 3         ┆ 2         │
│           ┆         ┆ 05:30:54   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 06:30:49  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 3       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 2.0       ┆ 14.0      ┆ 5         ┆ 3         │
│           ┆         ┆ 07:03:24   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 07:35:29  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 4       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 3101.0    ┆ 9261.0    ┆ 6         ┆ 20        │
│           ┆         ┆ 08:57:56   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 4       ┆ 2024-10-02 ┆ 2024-10-0 ┆ … ┆ 3101.0    ┆ 9261.0    ┆ 6         ┆ 3         │
│           ┆         ┆ 08:57:56   ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CEST       ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1         ┆ 70      ┆ 2025-12-03 ┆ 2025-12-0 ┆ … ┆ 2.0       ┆ 0.0       ┆ 2         ┆ 5         │
│           ┆         ┆ 03:26:48   ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 03:46:49  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 71      ┆ 2025-12-03 ┆ 2025-12-0 ┆ … ┆ 5.0       ┆ 16.0      ┆ 2         ┆ 9         │
│           ┆         ┆ 09:50:52   ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 10:05:32  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 72      ┆ 2025-12-03 ┆ 2025-12-0 ┆ … ┆ 17.0      ┆ 1.0       ┆ 3         ┆ 2         │
│           ┆         ┆ 15:28:13   ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 16:06:38  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 73      ┆ 2025-12-03 ┆ 2025-12-0 ┆ … ┆ 21.0      ┆ 3.0       ┆ 2         ┆ 9         │
│           ┆         ┆ 19:05:44   ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 19:12:02  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 1         ┆ 74      ┆ 2025-12-04 ┆ 2025-12-0 ┆ … ┆ 13.0      ┆ 36.0      ┆ 8         ┆ 2         │
│           ┆         ┆ 01:47:42   ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆ CET        ┆ 08:48:18  ┆   ┆           ┆           ┆           ┆           │
│           ┆         ┆            ┆ CET       ┆   ┆           ┆           ┆           ┆           │
└───────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘