In [1]:
import polars as pl
import yaml

with open("../config.budapest.yaml") as fp:
    config = yaml.safe_load(fp)

In [2]:
DIR = f"{config['dirs']['output']}/{config['city']}_ids_not_replaced"

In [3]:
for i in range(1):
    temp = pl.read_parquet(f"{DIR}/stops/v2/{i:02x}.parquet")

In [5]:
temp

shape: (548_130, 11)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id  ┆ stop_id ┆ interval_ ┆ interval_ ┆ … ┆ latitude_ ┆ longitude ┆ number_of ┆ place_lab │
│ ---        ┆ ---     ┆ start     ┆ stop      ┆   ┆ std       ┆ _std      ┆ _pings    ┆ el        │
│ str        ┆ i32     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ datetime[ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ u32       ┆ i64       │
│            ┆         ┆ μs, Europ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ e/Budapes ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ t]        ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 0.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 07:24:06  ┆ 07:35:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 2       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 1.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:23:47  ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 3       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:50:40  ┆ 10:58:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 4       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 12:41:20  ┆ 12:49:26  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 5       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 4         ┆ 12        │
│ 6276495c5a ┆         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 11:06:43  ┆ 11:22:57  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00ffd69f07 ┆ 381     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 14.0      ┆ 12.0      ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 18:27:21  ┆ 18:37:33  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 382     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 11.0      ┆ 6.0       ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 21:11:36  ┆ 21:26:20  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 383     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 9.0       ┆ 2.0       ┆ 4         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 04:47:22  ┆ 05:13:19  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 384     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 5.0       ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 08:04:50  ┆ 08:27:17  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 385     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 13.0      ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 09:08:14  ┆ 09:43:51  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
import polars_distance as pld

In [ ]:
data.select(
    pld.col("longitude_mean").dist.haversine("latitude_mean", "km").alias("haversine")
)

In [ ]:
data = temp.filter(pl.col.device_id.str.starts_with("0000051fc26276495c5a9ab1753a70"))[
    :3
].clone()

In [24]:
d = data.with_columns(
    pl.struct("longitude_mean", "latitude_mean")
    .alias("stop")
    .struct.rename_fields(["longitude", "latitude"]),
    pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean())
    .alias("centroid")
    .struct.rename_fields(["longitude", "latitude"]),
)
d

shape: (3, 13)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id  ┆ stop_id ┆ interval_ ┆ interval_ ┆ … ┆ number_of ┆ place_lab ┆ stop      ┆ centroid  │
│ ---        ┆ ---     ┆ start     ┆ stop      ┆   ┆ _pings    ┆ el        ┆ ---       ┆ ---       │
│ str        ┆ i32     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ struct[2] ┆ struct[2] │
│            ┆         ┆ datetime[ ┆ datetime[ ┆   ┆ u32       ┆ i64       ┆           ┆           │
│            ┆         ┆ μs, Europ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ e/Budapes ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ t]        ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 2         ┆ 11        ┆ {19.07635 ┆ {19.06433 │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 6,47.6611 ┆ 9,47.6069 │
│ 9ab1753a70 ┆         ┆ 07:24:06  ┆ 07:35:29  ┆   ┆           ┆           ┆ 66}       ┆ 28}       │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 2       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 2         ┆ 11        ┆ {19.07626 ┆ {19.06433 │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆ 2,47.6612 ┆ 9,47.6069 │
│ 9ab1753a70 ┆         ┆ 10:23:47  ┆ 10:33:00  ┆   ┆           ┆           ┆ 16}       ┆ 28}       │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 3       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 2         ┆ 12        ┆ {19.0404, ┆ {19.06433 │
│ 6276495c5a ┆         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆ 47.498402 ┆ 9,47.6069 │
│ 9ab1753a70 ┆         ┆ 10:50:40  ┆ 10:58:29  ┆   ┆           ┆           ┆ }         ┆ 28}       │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [25]:
d.with_columns(pld.col("centroid").dist.haversine("stop", "km").alias("haversine"))

shape: (3, 14)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id  ┆ stop_id ┆ interval_ ┆ interval_ ┆ … ┆ place_lab ┆ stop      ┆ centroid  ┆ haversine │
│ ---        ┆ ---     ┆ start     ┆ stop      ┆   ┆ el        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ i32     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ struct[2] ┆ struct[2] ┆ f64       │
│            ┆         ┆ datetime[ ┆ datetime[ ┆   ┆ i64       ┆           ┆           ┆           │
│            ┆         ┆ μs, Europ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ e/Budapes ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ t]        ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 11        ┆ {19.07635 ┆ {19.06433 ┆ 6.097816  │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆ 6,47.6611 ┆ 9,47.6069 ┆           │
│ 9ab1753a70 ┆         ┆ 07:24:06  ┆ 07:35:29  ┆   ┆           ┆ 66}       ┆ 28}       ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 2       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 11        ┆ {19.07626 ┆ {19.06433 ┆ 6.102335  │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆ 2,47.6612 ┆ 9,47.6069 ┆           │
│ 9ab1753a70 ┆         ┆ 10:23:47  ┆ 10:33:00  ┆   ┆           ┆ 16}       ┆ 28}       ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 3       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 12        ┆ {19.0404, ┆ {19.06433 ┆ 12.200559 │
│ 6276495c5a ┆         ┆ 3         ┆ 3         ┆   ┆           ┆ 47.498402 ┆ 9,47.6069 ┆           │
│ 9ab1753a70 ┆         ┆ 10:50:40  ┆ 10:58:29  ┆   ┆           ┆ }         ┆ 28}       ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
def rg(data):
    d = data.with_columns(
        pl.struct("longitude_mean", "latitude_mean").alias("stop"),
        pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean()).alias(
            "centroid"
        ),
    )
    d.with_columns(pld.col("centroid").dist.haversine("stop", "km").alias("haversine"))
    rcm_lon = data["longitude_mean"].mean()
    rcm_lat = data["latitude_mean"].mean()
    n = data["interval_lenght"].dt.seconds
    data["diff_lon"] = (data["longitude_mean"] - rcm_lon) ** 2
    data["diff_lat"] = (data["latitude_mean"] - rcm_lat) ** 2
    freq = data.groupby(["x", "y"])["t"].count().to_dict()

In [ ]:
temp.group_by(pl.col.device_id).with_columns(pl.col.longitude_mean)

In [ ]:
def calculate_radius_of_gyration(data, weighted: bool = False):
    rcm_lon = data["lon"].mean()
    rcm_lat = data["lat"].mean()
    freq = data.groupby(["x", "y"])["t"].count().to_dict()
    ds = []
    w = 0
    for row in data.itertuples():
        w += freq[(row.x, row.y)]
        d = haversine((rcm_lat, rcm_lon), (row.lat, row.lon), unit=Unit.METERS) ** 2
        if weighted:
            d *= freq[(row.x, row.y)]
        ds.append(d)

    sum_ = np.sum(ds)
    N = len(data)
    if weighted:
        N = w
    return np.round(np.sqrt(sum_ / N) / 1000, 3)